#!/usr/bin/env node
const readline = require('readline')
const crypto = require('crypto')

function hash(str) {
  return crypto.createHash('md5').update(str).digest('hex')
}

process.on('SIGINT', () => process.exit(0))
process.stdout.on('error', process.exit)
process.stdin.on('end', () => process.exit(0))
process.stdin.setEncoding('utf8')
const pipe = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false,
})

pipe.on('line', line => process.stdout.write(hash(line) + '\n'))
